# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------
"""
AllGatherMatmul Python Extension

Usage:
    python allgather_matmul.py --rank_size RANK_SIZE --rank_id RANK_ID --m M --n N --k K --data_dir DATA_DIR

Note: Input data (rank_i_a.bin, rank_i_b.bin) should be generated by gen_data.py first.
      Output will be written to DATA_DIR/output.bin
      Verification can be done by verify_result.py
"""
import os
from glob import glob
import argparse
import torch
import torch_npu


def load_torch_library(lib_name):
    """Load the libcatccos_torch.so library"""
    lib_env = "LD_LIBRARY_PATH" if os.name == "posix" else "PATH"
    lib_paths = os.environ.get(lib_env, "").split(os.pathsep)
    for path in lib_paths:
        if not os.path.isdir(path):
            continue
        match = glob(os.path.join(path, lib_name))
        if match:
            lib_path = match[0]
            torch.ops.load_library(lib_path)
            return
    raise FileNotFoundError(
        f"Library {lib_name} not found in {lib_env} paths, please check the environment variable or library path"
    )


def load_tensor_from_file(file_path, shape, dtype):
    """Load tensor from binary file"""
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Input file not found: {file_path}")

    # Calculate expected size
    element_size = 2 if dtype == torch.float16 else 4
    expected_size = shape[0] * shape[1] * element_size

    # Get actual file size
    file_size = os.path.getsize(file_path)

    # Verify file size matches expected size
    if file_size != expected_size:
        raise ValueError(
            f"File size mismatch: {file_path}, "
            f"expected {expected_size} bytes {shape}, "
            f"got {file_size} bytes"
        )

    # Read binary data
    total_elements = shape[0] * shape[1]
    data = torch.from_file(file_path, dtype=dtype, size=total_elements)
    data = data.contiguous().view(shape)
    return data


def worker(args):
    """Worker function for each rank"""
    rank_id = args.rank_id
    rank_size = args.rank_size
    m = args.m
    n = args.n
    k = args.k
    data_dir = args.data_dir
    ip_port = args.ip_port

    # Ensure data directory exists
    os.makedirs(data_dir, exist_ok=True)

    # Load torch library
    load_torch_library('libcatccos_torch.so')

    # Initialize shmem
    torch_npu.npu.set_device(rank_id)
    local_mem_size = 1024 * 1024 * 1024

    status = torch.ops.catccos.init(rank_id, rank_size, local_mem_size, ip_port)
    if status != 0:
        raise RuntimeError(f"Rank {rank_id}: torch.ops.catccos.init failed with status {status}")
    print(f"Rank {rank_id}: ACLCATCCOS init success!")

    try:
        # Load input tensors from files
        a_file = os.path.join(data_dir, f"rank_{rank_id}_a.bin")
        b_file = os.path.join(data_dir, f"rank_{rank_id}_b.bin")

        # Each rank has input shape (m, k) and (k, n)
        # Output shape is (m * rankSize, n) for allgather_matmul
        a_shape = (m, k)
        b_shape = (k, n)

        tensor_a = load_tensor_from_file(a_file, a_shape, torch.float16)
        tensor_b = load_tensor_from_file(b_file, b_shape, torch.float16)

        # Move to NPU
        tensor_a_npu = tensor_a.npu()
        tensor_b_npu = tensor_b.npu()

        # Execute kernel
        tensor_c_npu = torch.ops.catccos.allgather_matmul(tensor_a_npu, tensor_b_npu, rank_size)

        # Synchronize
        torch_npu.npu.synchronize()

        # Write output to file (only rank 0 writes)
        if rank_id == 0:
            c_output_file = os.path.join(data_dir, "output.bin")
            tensor_c_cpu = tensor_c_npu.cpu()

            with open(c_output_file, "wb") as f:
                f.write(tensor_c_cpu.numpy().tobytes())

            print(f"Rank {rank_id}: Done! Output written to {c_output_file}")
        else:
            print(f"Rank {rank_id}: Done!")
    finally:
        torch_npu.npu.synchronize()
        finalize_status = torch.ops.catccos.finalize()
        if finalize_status != 0:
            raise RuntimeError(
                f"Rank {rank_id}: torch.ops.catccos.finalize failed with status {finalize_status}"
            )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AllGatherMatmul Python Extension")

    parser.add_argument("--rank_size", type=int, required=True, help="Number of ranks")
    parser.add_argument("--rank_id", type=int, required=True, help="Current rank ID")
    parser.add_argument("--m", type=int, required=True, help="Matrix A rows")
    parser.add_argument("--n", type=int, required=True, help="Matrix B columns")
    parser.add_argument("--k", type=int, required=True, help="Matrix A columns / Matrix B rows")
    parser.add_argument("--data_dir", type=str, required=True, help="Data directory")
    parser.add_argument("--ip_port", type=str, default="tcp://127.0.0.1:8735", help="IP and port for shmem")

    print("NPU available:", torch_npu.npu.is_available())
    print("NPU device count:", torch_npu.npu.device_count())

    args = parser.parse_args()

    worker(args)
